openapi: 3.0.0
info:
  description: 按照票据模版，自动分割医疗票据
  title: 票据分割 API
  version: 0.9.0
servers:
- description: 内部测试地址
  url: http://localhost:5000/bill-segmentation
paths:
  /upload:
    post:
      operationId: upload_image
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/uploadPayloadDto'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/imgOnServerDto'
          description: OK
        "400":
          content:
            text/plain:
              schema:
                type: string
          description: 图像文件格式不正确（后缀不正确）
      summary: 上载文件
      x-openapi-router-controller: bill_segmentation.controllers.default_controller
  /version:
    get:
      operationId: get_version
      responses:
        "200":
          content:
            application/json:
              example:
                version: bill-segmentation-v0.9.0
              schema:
                $ref: '#/components/schemas/versionDto'
          description: 返回版本号
      summary: 获取 API 版本号
      x-openapi-router-controller: bill_segmentation.controllers.default_controller
  /wrap-perspective/{imgId}:
    post:
      operationId: wrap_perspective
      parameters:
      - description: 图像 ID
        explode: false
        in: path
        name: imgId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/roiPtsDto'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/imgOnServerDto'
          description: OK
        "400":
          content:
            text/plain:
              schema:
                type: string
          description: imgId 不正确
      summary: 对指定图像进行透视矫正
      x-openapi-router-controller: bill_segmentation.controllers.default_controller
  /wrap-segmentation/{billType}/{imgId}:
    get:
      operationId: wrap_segmentation
      parameters:
      - description: 票据类型 ID
        explode: false
        in: path
        name: billType
        required: true
        schema:
          type: string
        style: simple
      - description: 图像 ID
        explode: false
        in: path
        name: imgId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/wrapSegmentationResponseDto'
          description: OK
        "400":
          content:
            text/plain:
              schema:
                type: string
          description: 票据类型或票据 ID 不正确
      summary: 分割指定图像
      x-openapi-router-controller: bill_segmentation.controllers.default_controller
components:
  schemas:
    versionDto:
      example:
        version: version
      properties:
        version:
          title: version
          type: string
      title: versionDto
      type: object
    uploadPayloadDto:
      properties:
        file:
          format: binary
          type: string
      type: object
    imgOnServerDto:
      example:
        uploadImgUrl: uploadImgUrl
        uploadImgId: uploadImgId
      properties:
        uploadImgId:
          title: uploadImgId
          type: string
        uploadImgUrl:
          title: uploadImgUrl
          type: string
      title: imgOnServerDto
      type: object
    roiPtsDto:
      properties:
        roiPts:
          items:
            $ref: '#/components/schemas/roiPtsDto_roiPts'
          type: array
      type: object
    wrapSegmentationResponseDto:
      items:
        $ref: '#/components/schemas/imgOnServerDto'
      type: array
    roiPtsDto_roiPts:
      properties:
        x:
          title: x
          type: integer
        y:
          title: "y"
          type: integer
      title: roiPtsDto_roiPts
      type: object
