# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from bill_segmentation.models.base_model_ import Model
from bill_segmentation import util


class VersionDto(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, version=None):  # noqa: E501
        """VersionDto - a model defined in OpenAPI

        :param version: The version of this VersionDto.  # noqa: E501
        :type version: str
        """
        self.openapi_types = {
            'version': str
        }

        self.attribute_map = {
            'version': 'version'
        }

        self._version = version

    @classmethod
    def from_dict(cls, dikt) -> 'VersionDto':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The versionDto of this VersionDto.  # noqa: E501
        :rtype: VersionDto
        """
        return util.deserialize_model(dikt, cls)

    @property
    def version(self):
        """Gets the version of this VersionDto.


        :return: The version of this VersionDto.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this VersionDto.


        :param version: The version of this VersionDto.
        :type version: str
        """

        self._version = version
