# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from bill_segmentation.models.base_model_ import Model
from bill_segmentation.models.wrap_perspective_request_dto_roi_pts import WrapPerspectiveRequestDtoRoiPts
from bill_segmentation import util

from bill_segmentation.models.wrap_perspective_request_dto_roi_pts import WrapPerspectiveRequestDtoRoiPts  # noqa: E501

class WrapPerspectiveRequestDto(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, roi_pts=None):  # noqa: E501
        """WrapPerspectiveRequestDto - a model defined in OpenAPI

        :param roi_pts: The roi_pts of this WrapPerspectiveRequestDto.  # noqa: E501
        :type roi_pts: List[WrapPerspectiveRequestDtoRoiPts]
        """
        self.openapi_types = {
            'roi_pts': List[WrapPerspectiveRequestDtoRoiPts]
        }

        self.attribute_map = {
            'roi_pts': 'roiPts'
        }

        self._roi_pts = roi_pts

    @classmethod
    def from_dict(cls, dikt) -> 'WrapPerspectiveRequestDto':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The wrapPerspectiveRequestDto of this WrapPerspectiveRequestDto.  # noqa: E501
        :rtype: WrapPerspectiveRequestDto
        """
        return util.deserialize_model(dikt, cls)

    @property
    def roi_pts(self):
        """Gets the roi_pts of this WrapPerspectiveRequestDto.


        :return: The roi_pts of this WrapPerspectiveRequestDto.
        :rtype: List[WrapPerspectiveRequestDtoRoiPts]
        """
        return self._roi_pts

    @roi_pts.setter
    def roi_pts(self, roi_pts):
        """Sets the roi_pts of this WrapPerspectiveRequestDto.


        :param roi_pts: The roi_pts of this WrapPerspectiveRequestDto.
        :type roi_pts: List[WrapPerspectiveRequestDtoRoiPts]
        """

        self._roi_pts = roi_pts
