openapi: 3.0.0
info:
  title: 票据分割 API
  description: 按照票据模版，自动分割医疗票据
  version: 0.9.0

servers:
  - url: http://localhost:5000/bill-segmentation
    description: 内部测试地址

paths:
  /version:
    get:
      summary: 获取 API 版本号
      operationId: getVersion
      responses:
        "200": # status code
          description: 返回版本号
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/versionDto"
              example:
                version: "bill-segmentation-v0.9.0"

  /upload:
    post:
      summary: 上载文件
      operationId: uploadImage
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/uploadPayloadDto"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/imgOnServerDto"

  /wrap-perspective/{imgId}:
    post:
      summary: 对指定图像进行透视矫正
      operationId: wrapPerspective
      parameters:
        - name: imgId
          in: path
          description: 图像 ID
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/roiPtsDto"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/imgOnServerDto"
        "400":
          description: imgId 不正确
          content:
            text/plain:
              schema:
                type: string

  /wrap-segmentation/{billType}/{imgId}:
    get:
      summary: 分割指定图像
      operationId: wrapSegmentation
      parameters:
        - name: billType
          in: path
          description: 票据类型 ID
          required: true
          schema:
            type: string
        - name: imgId
          in: path
          description: 图像 ID
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/wrapSegmentationResponseDto"
        "400":
          description: 票据类型或票据 ID 不正确
          content:
            text/plain:
              schema:
                type: string

components:
  schemas:
    versionDto:
      type: object
      properties:
        version:
          type: string

    uploadPayloadDto:
      type: object
      properties:
        file:
          type: string
          format: binary

    imgOnServerDto:
      type: object
      properties:
        uploadImgId:
          type: string
        uploadImgUrl:
          type: string

    roiPtsDto:
      type: object
      properties:
        roiPts:
          type: array
          items:
            type: object
            properties:
              x:
                type: integer
              y:
                type: integer

    wrapSegmentationResponseDto:
      type: array
      items:
        $ref: "#/components/schemas/imgOnServerDto"
