openapi: 3.0.0
info:
  title: 票据分割 API
  description: 按照票据模版，自动分割医疗票据
  version: 0.9.0

servers:
  - url: http://localhost:5000/bill-segmentation
    description: 内部测试地址

paths:
  /version:
    get:
      summary: 获取 API 版本号
      operationId: getVersion
      responses:
        "200": # status code
          description: 返回版本号
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/versionDto"
              example:
                version: "bill-segmentation-v0.9.0"

  /upload:
    post:
      summary: 上载文件
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/uploadPayload"
      responses:
        "200":
          description: OK

components:
  schemas:
    versionDto:
      type: object
      properties:
        version:
          type: string

    uploadPayload:
      type: object
      properties:
        file:
          type: string
          format: binary
